# Generated by Django 3.0 on 2023-11-21 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
    ]
