# Generated by Django 3.0 on 2023-11-21 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20231121_0321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'Profiles'},
        ),

        migrations.RunSQL("""
            INSERT INTO profiles_profile (
                id,
                favorite_city,
                user_id
            )
            SELECT
                id,
                favorite_city,
                user_id
            FROM
                oc_lettings_site_profile;
        """, reverse_sql="""
            INSERT INTO oc_lettings_site_profile (
                id,
                favorite_city,
                user_id
            )
            SELECT
                id,
                favorite_city,
                user_id
            FROM
                oc_lettings_site_profile;
        """),
    ]
