# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  python: circleci/python@2.1.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  run_tests_suite:
    executor: python/default
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    #docker:
      #- image: cimg/base:stable
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: "run_pytest"
          command: |
            python manage.py collectstatic
            python -m pytest
      - run:
          name: "run_flake8"
          command: |
            flake8 --extend-ignore=E251,E501,E712 lettings/ profiles/ oc_lettings_site/

  build_docker_image:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      #- image: cimg/base:stable
      - image: cimg/python:3.8.6-browsers
        auth:
            username: $DOCKERHUB_USERNAME
            password: $DOCKERHUB_TOKEN
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "build_image"
          command: |
            docker build -t $IMAGE_NAME:latest .
      - run:
          name: "push_image"
          command: |
            docker images
            echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest

  deploy_on_render:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      #- image: cimg/base:stable
      - image: cimg/python:3.8.6-browsers
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: "deploy_container"
          command: curl -X GET $WEBHOOK_URL
      - run:
          name: "run_test"
          command: "echo Hello, World!"
# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  oc_lettings-deployement:
    jobs:
      - run_tests_suite
      - build_docker_image:
          requires:
            - run_tests_suite
      - deploy_on_render:
          requires:
            - build_docker_image