# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  executor:
        name: python/default
        tag: '3.8.6'
  run_tests:
    steps:
        -checkout
        -python/install-packages:
            pkg-manager: pip
        -run:
            name: pytest-tests
            command: |
              python -m pytest
            
          # coverage run -m pytest 
          # coverage report --fail-under=80
        -run:
            name: flake8
            command : |
              flake8 --format=html --htmldir=flake-report --extend-ignore=E251,E501,E712 lettings/ profiles/ oc_lettings_site/

        -persist_to_workspace:
            root: .
            paths:
              - .

  build_image:
    docker:
      -image: circleci/python:3.8.6-browsers
        #auth:
          #username: $DOCKERHUB_USERNAME
          #password: $DOCKERHUB_TOKEN
    steps:
      -checkout
      -setup_remote_docker
      -run:
          name: build-image
          command: |
            docker build -t oc_lettings_django:latest .
      - run:
          name: push-image
          command: |
            docker login -u "$DOCKERHUB_USERNAME" --password-stdin "$DOCKERHUB_TOKEN" docker.io
            docker push lisa367/oc_lettings_django:latest

  deploy_app:
    docker:
      - image:circleci/python:3.8.6-browsers
    steps:
      -checkout
      -run:
          name: deploy-image
          command: curl -X GET $WEBHOOK_URL https://api.render.com/deploy/srv-cm08gn6d3nmc738lg3gg?key=zq1NrtVz-3I



workflows:
  build_test_deploy:
    jobs:
      - run_tests
      #- build_image
          #requires:
            #- run-tests
      #- deploy_app
          #requires:
            #- run-tests
            #- build-image

